apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kdoctorController.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
  {{- if or .Values.global.commonAnnotations .Values.kdoctorController.service.annotations }}
  annotations:
    {{- if .Values.global.commonAnnotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.kdoctorController.service.annotations }}
    {{- include "tplvalues.render" ( dict "value" .Values.kdoctorController.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- include "project.kdoctorController.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kdoctorController.service.type }}
  ports:
    {{- if .Values.kdoctorController.prometheus.enabled }}
    - name: metrics
      port: {{ .Values.kdoctorController.prometheus.port }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
    - name: webhook
      port: {{ .Values.kdoctorController.webhookPort }}
      targetPort: webhook
      protocol: TCP
    - name: apiserver
      port: 443
      targetPort: apiserver
      protocol: TCP
  selector:
    {{- include "project.kdoctorController.selectorLabels" . | nindent 4 }}
