{{- $_ := include "generate-ca-certs" . }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Values.kdoctorController.name | trunc 63 | trimSuffix "-" }}
  annotations:
    {{- if (eq .Values.tls.server.method "certmanager") }}
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ .Values.kdoctorController.name | trunc 63 | trimSuffix "-" }}-server-certs
    {{- end }}
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ .Values.kdoctorController.name | trunc 63 | trimSuffix "-" }}
        namespace: {{ .Release.Namespace }}
        path: "/mutate-kdoctor-io-v1beta1-apphttphealthy"
        port: {{ .Values.kdoctorController.webhookPort }}
      {{- if (eq .Values.tls.server.method "provided") }}
      caBundle: {{ .Values.tls.server.provided.tlsCa | required "missing tls.provided.tlsCa" }}
      {{- else if (eq .Values.tls.server.method "auto") }}
      caBundle: {{ .ca.Cert | b64enc }}
      {{- end }}
    failurePolicy: Fail
    sideEffects: None
    name: apphttphealthy.kdoctor.io
    rules:
      - apiGroups:
          # ====modify====
          - kdoctor.io
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - apphttphealthies
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ .Values.kdoctorController.name | trunc 63 | trimSuffix "-" }}
        namespace: {{ .Release.Namespace }}
        path: "/mutate-kdoctor-io-v1beta1-netreach"
        port: {{ .Values.kdoctorController.webhookPort }}
      {{- if (eq .Values.tls.server.method "provided") }}
      caBundle: {{ .Values.tls.server.provided.tlsCa | required "missing tls.provided.tlsCa" }}
      {{- else if (eq .Values.tls.server.method "auto") }}
      caBundle: {{ .ca.Cert | b64enc }}
      {{- end }}
    failurePolicy: Fail
    sideEffects: None
    name: netreach.kdoctor.io
    rules:
      - apiGroups:
          # ====modify====
          - kdoctor.io
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          # ====modify==== crdName
          - netreaches
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ .Values.kdoctorController.name | trunc 63 | trimSuffix "-" }}
        namespace: {{ .Release.Namespace }}
        path: "/mutate-kdoctor-io-v1beta1-netdns"
        port: {{ .Values.kdoctorController.webhookPort }}
      {{- if (eq .Values.tls.server.method "provided") }}
      caBundle: {{ .Values.tls.server.provided.tlsCa | required "missing tls.provided.tlsCa" }}
      {{- else if (eq .Values.tls.server.method "auto") }}
      caBundle: {{ .ca.Cert | b64enc }}
      {{- end }}
    failurePolicy: Fail
    sideEffects: None
    # ====modify====
    name: netdns.kdoctor.io
    rules:
      - apiGroups:
          - kdoctor.io
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - netdnses
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Values.kdoctorController.name | trunc 63 | trimSuffix "-" }}
  annotations:
    {{- if (eq .Values.tls.server.method "certmanager") }}
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ .Values.kdoctorController.name | trunc 63 | trimSuffix "-" }}-server-certs
    {{- end }}
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ .Values.kdoctorController.name | trunc 63 | trimSuffix "-" }}
        namespace: {{ .Release.Namespace }}
        path: "/validate-kdoctor-io-v1beta1-apphttphealthy"
        port: {{ .Values.kdoctorController.webhookPort }}
      {{- if (eq .Values.tls.server.method "provided") }}
      caBundle: {{ .Values.tls.server.provided.tlsCa | required "missing tls.provided.tlsCa" }}
      {{- else if (eq .Values.tls.server.method "auto") }}
      caBundle: {{ .ca.Cert | b64enc }}
      {{- end }}
    failurePolicy: Fail
    name: apphttphealthy.kdoctor.io
    sideEffects: None
    rules:
      - apiGroups:
          - kdoctor.io
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - apphttphealthies
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ .Values.kdoctorController.name | trunc 63 | trimSuffix "-" }}
        namespace: {{ .Release.Namespace }}
        path: "/validate-kdoctor-io-v1beta1-netreach"
        port: {{ .Values.kdoctorController.webhookPort }}
      {{- if (eq .Values.tls.server.method "provided") }}
      caBundle: {{ .Values.tls.server.provided.tlsCa | required "missing tls.provided.tlsCa" }}
      {{- else if (eq .Values.tls.server.method "auto") }}
      caBundle: {{ .ca.Cert | b64enc }}
      {{- end }}
    failurePolicy: Fail
    name: netreach.kdoctor.io
    sideEffects: None
    rules:
      - apiGroups:
          - kdoctor.io
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - netreaches
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ .Values.kdoctorController.name | trunc 63 | trimSuffix "-" }}
        namespace: {{ .Release.Namespace }}
        path: "/validate-kdoctor-io-v1beta1-netdns"
        port: {{ .Values.kdoctorController.webhookPort }}
      {{- if (eq .Values.tls.server.method "provided") }}
      caBundle: {{ .Values.tls.server.provided.tlsCa | required "missing tls.provided.tlsCa" }}
      {{- else if (eq .Values.tls.server.method "auto") }}
      caBundle: {{ .ca.Cert | b64enc }}
      {{- end }}
    failurePolicy: Fail
    name: netdns.kdoctor.io
    sideEffects: None
    rules:
      - apiGroups:
          - kdoctor.io
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - netdnses

{{- if eq .Values.tls.server.method "certmanager" -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.kdoctorController.name | trunc 63 | trimSuffix "-" }}-server-certs
  namespace: {{ .Release.Namespace }}
spec:
  issuerRef:
    name: {{ .Values.tls.server.certmanager.issuerName | trunc 63 | trimSuffix "-" }}
  secretName: {{ .Values.tls.server.secretName | trunc 63 | trimSuffix "-" }}
  commonName: {{ .Values.kdoctorController.name | trunc 63 | trimSuffix "-" }}.{{ .Release.Namespace }}.svc
  dnsNames:
    - {{ .Values.kdoctorController.name | trunc 63 | trimSuffix "-" }}
    - {{ .Values.kdoctorController.name | trunc 63 | trimSuffix "-" }}.{{ .Release.Namespace }}
    - {{ .Values.kdoctorController.name | trunc 63 | trimSuffix "-" }}.{{ .Release.Namespace }}.svc
    - {{ .Values.kdoctorController.name | trunc 63 | trimSuffix "-" }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDnsDomain }}
  {{- range $dns := .Values.tls.server.certmanager.extraDnsNames }}
    - {{ $dns | quote }}
  {{- end }}
  {{- if .Values.tls.server.certmanager.extraIPAddresses }}
  ipAddresses:
  {{- range $ip := .Values.tls.server.certmanager.extraIPAddresses }}
    - {{ $ip | quote }}
  {{- end }}
  {{- end }}
  duration: {{ printf "%dh" (mul .Values.tls.server.certmanager.certValidityDuration 24) }}
  {{- end }}

{{- if (eq .Values.tls.server.method "provided") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.server.secretName | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  ca.crt:  {{ .Values.tls.server.provided.tlsCa | required "missing tls.provided.tlsCa" }}
  tls.crt: {{ .Values.tls.server.provided.tlsCert | required "missing tls.provided.tlsCert" }}
  tls.key: {{ .Values.tls.server.provided.tlsKey  | required "missing tls.provided.tlsKey"  }}
  {{- end }}

{{- if eq .Values.tls.server.method "auto" }}
---
{{- $cn := printf "kdoctor.io" }}
{{- $ip := .Values.tls.server.auto.extraIpAddresses }}
{{- $dns1 := printf "%s.%s" .Values.kdoctorController.name .Release.Namespace }}
{{- $dns2 := printf "%s.%s.svc" .Values.kdoctorController.name .Release.Namespace }}
{{- $dns3 := printf "%s.%s.svc.%s" .Values.kdoctorController.name .Release.Namespace .Values.global.clusterDnsDomain }}
{{- $dns := prepend .Values.tls.server.auto.extraDnsNames $dns1 }}
{{- $dns = prepend $dns $dns2 }}
{{- $dns = prepend $dns $dns3 }}
{{- $dns = prepend $dns $cn }}
{{- $cert := genSignedCert $cn $ip $dns (.Values.tls.server.auto.certExpiration | int) .ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.server.secretName | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  ca.crt:  {{ .ca.Cert | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key  | b64enc }}
{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.ca.secretName | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt:  {{ .ca.Cert | b64enc }}
  tls.key:  {{ .ca.Key  | b64enc }}

---
{{- $cn := printf "kdoctor.io" }}
{{- $cert := genSignedCert $cn (list) (list) 73000 .ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.client.secretName | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  ca.crt:  {{ .ca.Cert | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key  | b64enc }}
