# https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md
swagger: "2.0"
info:
  description: agent http server
  title: http server API
  version: v1
x-schemes:
  - http
basePath: "/"
produces:
  - application/json
consumes:
  - application/json
paths:
  "/healthy/startup":
    get:
      summary: Startup probe
      description: pod startup probe for agent and controller pod
      tags:
        - healthy
      responses:
        "200":
          description: Success
        "500":
          description: Failed
  "/healthy/readiness":
    get:
      summary: Readiness probe
      description: pod readiness probe for agent and controller pod
      tags:
        - healthy
      responses:
        "200":
          description: Success
        "500":
          description: Failed
  "/healthy/liveness":
    get:
      summary: Liveness probe
      description: pod liveness probe for agent and controller pod
      tags:
        - healthy
      responses:
        "200":
          description: Success
        "500":
          description: Failed
  "/":
    get:
      summary: echo http request
      description: echo http request
      tags:
        - echo
      parameters:
        - in: query
          name: delay
          type: integer
          description: delay some second return response
        - in: query
          name: task
          type: string
          description: task name
      responses:
        "200":
          description: Success
          schema:
            "$ref": "#/definitions/EchoRes"
    post:
      summary: echo http request counts
      description: echo http request counts
      tags:
        - echo
      parameters:
        - name: test-args
          in: body
          required: true
          schema:
            $ref: "#/definitions/EchoBody"
        - in: query
          name: delay
          type: integer
          description: delay some second return response
        - in: query
          name: task
          type: string
          description: task name
      responses:
        "200":
          description: Success
        "500":
          description: Failed
    delete:
      summary: clean http request counts
      description: clean http request counts
      tags:
        - echo
      parameters:
        - in: query
          name: task
          type: string
          description: task name
      responses:
        "200":
          description: Success
        "500":
          description: Failed
    put:
      summary: echo http request
      description: echo http request
      tags:
        - echo
      parameters:
        - in: query
          name: delay
          type: integer
          description: delay some second return response
        - in: query
          name: task
          type: string
          description: task name
      responses:
        "200":
          description: Success
        "500":
          description: Failed
    head:
      summary: echo http request
      description: echo http request
      tags:
        - echo
      parameters:
        - in: query
          name: delay
          type: integer
          description: delay some second return response
        - in: query
          name: task
          type: string
          description: task name
      responses:
        "200":
          description: Success
        "500":
          description: Failed
    patch:
      summary: echo http request
      description: echo http request
      tags:
        - echo
      parameters:
        - in: query
          name: delay
          type: integer
          description: delay some second return response
        - in: query
          name: task
          type: string
          description: task name
      responses:
        "200":
          description: Success
        "500":
          description: Failed
    options:
      summary: echo http request
      description: echo http request
      tags:
        - echo
      parameters:
        - in: query
          name: delay
          type: integer
          description: delay some second return response
        - in: query
          name: task
          type: string
          description: task name
      responses:
        "200":
          description: Success
        "500":
          description: Failed
  "/kdoctoragent":
    get:
      summary: echo http request
      description: echo http request
      tags:
        - echo
      parameters:
        - in: query
          name: delay
          type: integer
          description: delay some second return response
        - in: query
          name: task
          type: string
          description: task name
      responses:
        "200":
          description: Success
          schema:
            "$ref": "#/definitions/EchoRes"
    post:
      summary: echo http request counts
      description: echo http request counts
      tags:
        - echo
      parameters:
        - name: test-args
          in: body
          required: true
          schema:
            $ref: "#/definitions/EchoBody"
        - in: query
          name: delay
          type: integer
          description: delay some second return response
        - in: query
          name: task
          type: string
          description: task name
      responses:
        "200":
          description: Success
        "500":
          description: Failed
    delete:
      summary: clean http request counts
      description: clean http request counts
      tags:
        - echo
      parameters:
        - in: query
          name: task
          type: string
          description: task name
      responses:
        "200":
          description: Success
        "500":
          description: Failed
    put:
      summary: echo http request
      description: echo http request
      tags:
        - echo
      parameters:
        - in: query
          name: delay
          type: integer
          description: delay some second return response
        - in: query
          name: task
          type: string
          description: task name
      responses:
        "200":
          description: Success
        "500":
          description: Failed
    head:
      summary: echo http request
      description: echo http request
      tags:
        - echo
      parameters:
        - in: query
          name: delay
          type: integer
          description: delay some second return response
        - in: query
          name: task
          type: string
          description: task name
      responses:
        "200":
          description: Success
        "500":
          description: Failed
    patch:
      summary: echo http request
      description: echo http request
      tags:
        - echo
      parameters:
        - in: query
          name: delay
          type: integer
          description: delay some second return response
        - in: query
          name: task
          type: string
          description: task name
      responses:
        "200":
          description: Success
        "500":
          description: Failed
    options:
      summary: echo http request
      description: echo http request
      tags:
        - echo
      parameters:
        - in: query
          name: delay
          type: integer
          description: delay some second return response
        - in: query
          name: task
          type: string
          description: task name
      responses:
        "200":
          description: Success
        "500":
          description: Failed
definitions:
  EchoRes:
    description: echo request
    type: object
    properties:
      serverName:
        description: server host name
        type: string
      clientIp:
        description: client source ip
        type: string
      requestUrl:
        description: request url
        type: string
      requestMethod:
        description: request method
        type: string
      requestHeader:
        description: request header
        type: object
        additionalProperties:
          type: string
      requestCount:
        description: request count
        type: integer
      TaskName:
        description: task name
        type: string
      requestParam:
        description: request param
        type: string
      requestBody:
        description: request body
        type: string
      supportedMethod:
        description: request body
        type: array
        items:
          type: string
      paramDetail:
        description: param detail
        type: object
        additionalProperties:
          type: string
  EchoBody:
    description: echo request body args
    type: object
    properties:
      test1:
        type: string
      test2:
        type: string
